tap "int128/kubelogin", trusted: { formula: "kubelogin" }
tap "nikitabobko/tap", trusted: { cask: "aerospace" }

brew "tree"
brew "ansible"
brew "atuin"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "docker"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "go"
brew "golangci-lint"
brew "imagemagick"
brew "jq"
brew "kind"
brew "kubernetes-cli"
brew "kubie"
brew "kyverno"
brew "m1ddc"
brew "restic"
brew "ripgrep"
brew "tfenv"
brew "tgenv"
brew "tmux"
brew "watch"
brew "wget"
brew "yq"
brew "zsh"
brew "int128/kubelogin/kubelogin"

cask "aerospace"
cask "ghostty"
cask "figma"
cask "font-hasklig"
cask "obsidian"
cask "signal"
cask "spotify"
cask "handy"
cask "zed"
